// Decompiled with JetBrains decompiler
// Type: Qios.DevSuite.Components.QBaseShapeCollection
// Assembly: Qios.DevSuite.Components, Version=4.0.0.20, Culture=neutral, PublicKeyToken=3cc53827b79c92fa
// MVID: CBFDE16D-813F-43A0-8BDF-661C2FBF9FBE
// Assembly location: C:\dev\trevorde\WaveletStudio\trunk\res\libs\Qios\Qios.DevSuite.Components.dll

using System.Drawing;
using System.Windows.Forms;

namespace Qios.DevSuite.Components
{
  public class QBaseShapeCollection : QShapeCollection
  {
    public QBaseShapeCollection()
    {
      QBaseShape shape1 = new QBaseShape(QBaseShapeType.RectangleShape.ToString(), QBaseShapeType.RectangleShape, new Size(100, 20), new Rectangle(2, 2, 96, 16));
      shape1.SetShapeType(QShapeType.Generic);
      shape1.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape1.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape1.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape1.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape1.ResetChanged();
      this.Add((QShape) shape1);
      QBaseShape shape2 = new QBaseShape(QBaseShapeType.SquareTabStripNavigationArea.ToString(), QBaseShapeType.SquareTabStripNavigationArea, new Size(100, 20), new Rectangle(2, 2, 96, 16));
      shape2.SetShapeType(QShapeType.TabStripNavigationArea);
      shape2.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape2.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, false));
      shape2.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, false));
      shape2.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape2.ResetChanged();
      this.Add((QShape) shape2);
      QBaseShape shape3 = new QBaseShape(QBaseShapeType.LeftCurvedTabStripNavigationArea.ToString(), QBaseShapeType.LeftCurvedTabStripNavigationArea, new Size(100, 20), new Rectangle(15, 2, 80, 16));
      shape3.SetShapeType(QShapeType.TabStripNavigationArea);
      shape3.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape3.Items.Add(new QShapeItem(12f, 5f, 15f, 1f, 17f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape3.Items.Add(new QShapeItem(23f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape3.Items.Add(new QShapeItem(99f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, false));
      shape3.Items.Add(new QShapeItem(99f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape3.ResetChanged();
      this.Add((QShape) shape3);
      QBaseShape shape4 = new QBaseShape(QBaseShapeType.RoundedTabStripNavigationArea.ToString(), QBaseShapeType.RoundedTabStripNavigationArea, new Size(100, 20), new Rectangle(10, 2, 80, 16));
      shape4.SetShapeType(QShapeType.TabStripNavigationArea);
      shape4.Items.Add(new QShapeItem(0.0f, 20f, 4f, 20f, 7f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape4.Items.Add(new QShapeItem(7f, 13f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape4.Items.Add(new QShapeItem(7f, 8f, 7f, 4f, 7f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape4.Items.Add(new QShapeItem(12f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape4.Items.Add(new QShapeItem(88f, 0.0f, 93f, 0.0f, 93f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape4.Items.Add(new QShapeItem(93f, 8f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape4.Items.Add(new QShapeItem(93f, 13f, 93f, 20f, 96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape4.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape4.ResetChanged();
      this.Add((QShape) shape4);
      QBaseShape shape5 = new QBaseShape(QBaseShapeType.SquareTabStrip.ToString(), QBaseShapeType.SquareTabStrip, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape5.SetShapeType(QShapeType.TabStrip);
      shape5.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, false));
      shape5.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, false));
      shape5.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, false));
      shape5.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape5.ResetChanged();
      this.Add((QShape) shape5);
      QBaseShape shape6 = new QBaseShape(QBaseShapeType.RoundedTabStrip.ToString(), QBaseShapeType.RoundedTabStrip, new Size(100, 20), new Rectangle(10, 0, 80, 20));
      shape6.SetShapeType(QShapeType.TabStrip);
      shape6.Items.Add(new QShapeItem(0.0f, 20f, 4f, 20f, 7f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape6.Items.Add(new QShapeItem(7f, 13f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape6.Items.Add(new QShapeItem(7f, 8f, 7f, 4f, 7f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape6.Items.Add(new QShapeItem(12f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape6.Items.Add(new QShapeItem(88f, 0.0f, 93f, 0.0f, 93f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape6.Items.Add(new QShapeItem(93f, 8f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape6.Items.Add(new QShapeItem(93f, 13f, 93f, 20f, 96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape6.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape6.ResetChanged();
      this.Add((QShape) shape6);
      QBaseShape shape7 = new QBaseShape(QBaseShapeType.SquareTab.ToString(), QBaseShapeType.SquareTab, new Size(100, 20), new Rectangle(2, 2, 96, 16));
      shape7.SetShapeType(QShapeType.TabButton);
      shape7.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape7.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape7.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape7.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape7.ResetChanged();
      this.Add((QShape) shape7);
      QBaseShape shape8 = new QBaseShape(QBaseShapeType.RoundedTab.ToString(), QBaseShapeType.RoundedTab, new Size(100, 20), new Rectangle(10, 2, 80, 16));
      shape8.SetShapeType(QShapeType.TabButton);
      shape8.Items.Add(new QShapeItem(0.0f, 20f, 4f, 20f, 7f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape8.Items.Add(new QShapeItem(7f, 13f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape8.Items.Add(new QShapeItem(7f, 8f, 7f, 4f, 7f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape8.Items.Add(new QShapeItem(12f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape8.Items.Add(new QShapeItem(88f, 0.0f, 93f, 0.0f, 93f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape8.Items.Add(new QShapeItem(93f, 8f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape8.Items.Add(new QShapeItem(93f, 13f, 93f, 20f, 96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape8.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape8.ResetChanged();
      this.Add((QShape) shape8);
      QBaseShape shape9 = new QBaseShape(QBaseShapeType.MSOneNoteTab.ToString(), QBaseShapeType.MSOneNoteTab, new Size(100, 20), new Rectangle(28, 2, 62, 16));
      shape9.SetShapeType(QShapeType.TabButton);
      shape9.Items.Add(new QShapeItem(0.0f, 20f, 4f, 20f, 6f, 18f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape9.Items.Add(new QShapeItem(9f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape9.Items.Add(new QShapeItem(21f, 6f, 24f, 4f, 28f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape9.Items.Add(new QShapeItem(32f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape9.Items.Add(new QShapeItem(87f, 0.0f, 93f, 0.0f, 93f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape9.Items.Add(new QShapeItem(93f, 8f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape9.Items.Add(new QShapeItem(93f, 13f, 93f, 17f, 95f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape9.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape9.ResetChanged();
      this.Add((QShape) shape9);
      QBaseShape shape10 = new QBaseShape(QBaseShapeType.MSVisualStudio2005Tab.ToString(), QBaseShapeType.MSVisualStudio2005Tab, new Size(100, 20), new Rectangle(15, 2, 80, 16));
      shape10.SetShapeType(QShapeType.TabButton);
      shape10.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape10.Items.Add(new QShapeItem(12f, 5f, 15f, 1f, 17f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape10.Items.Add(new QShapeItem(23f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape10.Items.Add(new QShapeItem(90f, 0.0f, 96f, 0.0f, 96f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape10.Items.Add(new QShapeItem(96f, 8f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape10.Items.Add(new QShapeItem(96f, 13f, 96f, 20f, 96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape10.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape10.ResetChanged();
      this.Add((QShape) shape10);
      QBaseShape shape11 = new QBaseShape(QBaseShapeType.RibbonTabButton.ToString(), QBaseShapeType.RibbonTabButton, new Size(100, 20), new Rectangle(2, 2, 96, 16));
      shape11.SetShapeType(QShapeType.TabButton);
      shape11.Items.Add(new QShapeItem(0.0f, 20f, 2f, 19f, 2f, 19f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape11.Items.Add(new QShapeItem(2f, 17f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape11.Items.Add(new QShapeItem(2f, 4f, 2f, 1f, 3f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape11.Items.Add(new QShapeItem(5f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape11.Items.Add(new QShapeItem(95f, 0.0f, 97f, 0.0f, 98f, 1f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape11.Items.Add(new QShapeItem(98f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape11.Items.Add(new QShapeItem(98f, 17f, 98f, 19f, 98f, 19f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape11.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, false));
      shape11.ResetChanged();
      this.Add((QShape) shape11);
      QBaseShape shape12 = new QBaseShape(QBaseShapeType.SquareContent.ToString(), QBaseShapeType.SquareContent, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape12.SetShapeType(QShapeType.Content);
      shape12.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape12.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape12.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape12.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape12.ResetChanged();
      this.Add((QShape) shape12);
      QBaseShape shape13 = new QBaseShape(QBaseShapeType.RoundedContent.ToString(), QBaseShapeType.RoundedContent, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape13.SetShapeType(QShapeType.Content);
      shape13.Items.Add(new QShapeItem(4f, 20f, 2f, 20f, 0.0f, 18f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape13.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape13.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape13.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape13.Items.Add(new QShapeItem(96f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape13.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape13.Items.Add(new QShapeItem(100f, 16f, 100f, 18f, 98f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape13.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape13.ResetChanged();
      this.Add((QShape) shape13);
      QBaseShape shape14 = new QBaseShape(QBaseShapeType.RoundedContent2.ToString(), QBaseShapeType.RoundedContent2, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape14.SetShapeType(QShapeType.Content);
      shape14.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape14.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape14.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape14.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape14.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape14.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape14.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape14.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape14.ResetChanged();
      this.Add((QShape) shape14);
      QBaseShape shape15 = new QBaseShape(QBaseShapeType.TabControlContent.ToString(), QBaseShapeType.TabControlContent, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape15.SetShapeType(QShapeType.Content);
      shape15.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape15.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape15.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape15.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape15.ResetChanged();
      this.Add((QShape) shape15);
      QBaseShape shape16 = new QBaseShape(QBaseShapeType.RibbonContent.ToString(), QBaseShapeType.RibbonContent, new Size(100, 50), new Rectangle(2, 2, 94, 44));
      shape16.SetShapeType(QShapeType.Content);
      shape16.Items.Add(new QShapeItem(4f, 47f, 2f, 47f, 0.0f, 45f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape16.Items.Add(new QShapeItem(0.0f, 43f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape16.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape16.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, false));
      shape16.Items.Add(new QShapeItem(93f, 0.0f, 95f, 0.0f, 97f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape16.Items.Add(new QShapeItem(97f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape16.Items.Add(new QShapeItem(97f, 43f, 97f, 45f, 95f, 47f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape16.Items.Add(new QShapeItem(93f, 47f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape16.ResetChanged();
      this.Add((QShape) shape16);
      QBaseShape shape17 = new QBaseShape(QBaseShapeType.RibbonPanel.ToString(), QBaseShapeType.RibbonPanel, new Size(100, 50), new Rectangle(0, 0, 100, 50));
      shape17.SetShapeType(QShapeType.Content);
      shape17.Items.Add(new QShapeItem(4f, 50f, 2f, 50f, 0.0f, 48f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape17.Items.Add(new QShapeItem(0.0f, 46f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape17.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape17.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape17.Items.Add(new QShapeItem(96f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape17.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape17.Items.Add(new QShapeItem(100f, 46f, 100f, 48f, 98f, 50f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape17.Items.Add(new QShapeItem(96f, 50f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape17.ResetChanged();
      this.Add((QShape) shape17);
      QBaseShape shape18 = new QBaseShape(QBaseShapeType.RibbonItemBar.ToString(), QBaseShapeType.RibbonItemBar, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape18.SetShapeType(QShapeType.Content);
      shape18.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape18.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape18.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape18.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape18.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape18.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape18.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape18.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape18.ResetChanged();
      this.Add((QShape) shape18);
      QBaseShape shape19 = new QBaseShape(QBaseShapeType.RibbonLaunchBar.ToString(), QBaseShapeType.RibbonLaunchBar, new Size(100, 22), new Rectangle(12, 0, 80, 22));
      shape19.SetShapeType(QShapeType.Content);
      shape19.Items.Add(new QShapeItem(100f, 13f, 100f, 18f, 96f, 22f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape19.Items.Add(new QShapeItem(92f, 22f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape19.Items.Add(new QShapeItem(11f, 22f, 12f, 14f, 10f, 4f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape19.Items.Add(new QShapeItem(1f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape19.Items.Add(new QShapeItem(92f, 0.0f, 96f, 0.0f, 100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape19.Items.Add(new QShapeItem(100f, 9f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape19.ResetChanged();
      this.Add((QShape) shape19);
      QBaseShape shape20 = new QBaseShape(QBaseShapeType.RibbonLaunchBarHost.ToString(), QBaseShapeType.RibbonLaunchBarHost, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape20.SetShapeType(QShapeType.Content);
      shape20.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape20.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape20.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape20.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape20.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape20.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape20.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape20.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape20.ResetChanged();
      this.Add((QShape) shape20);
      QBaseShape shape21 = new QBaseShape(QBaseShapeType.RibbonCaption.ToString(), QBaseShapeType.RibbonCaption, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape21.SetShapeType(QShapeType.Content);
      shape21.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, false));
      shape21.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, false));
      shape21.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, false));
      shape21.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape21.ResetChanged();
      this.Add((QShape) shape21);
      QBaseShape shape22 = new QBaseShape(QBaseShapeType.BalloonShapedWindow.ToString(), QBaseShapeType.BalloonShapedWindow, new Size(100, 50), new Rectangle(10, 20, 80, 20));
      shape22.SetShapeType(QShapeType.ShapedWindow);
      shape22.Items.Add(new QShapeItem(0.0f, 23f, 0.0f, 18f, 5f, 13f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape22.Items.Add(new QShapeItem(10f, 13f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape22.Items.Add(new QShapeItem(10f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape22.Items.Add(new QShapeItem(25f, 13f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape22.Items.Add(new QShapeItem(90f, 13f, 95f, 13f, 100f, 18f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape22.Items.Add(new QShapeItem(100f, 23f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape22.Items.Add(new QShapeItem(100f, 40f, 100f, 45f, 95f, 50f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape22.Items.Add(new QShapeItem(90f, 50f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape22.Items.Add(new QShapeItem(10f, 50f, 5f, 50f, 0.0f, 45f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape22.Items.Add(new QShapeItem(0.0f, 40f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape22.ResetChanged();
      this.Add((QShape) shape22);
      QBaseShape shape23 = new QBaseShape(QBaseShapeType.ArrowBalloonShapedWindow.ToString(), QBaseShapeType.ArrowBalloonShapedWindow, new Size(100, 50), new Rectangle(2, 19, 96, 29));
      shape23.SetShapeType(QShapeType.ShapedWindow);
      shape23.Items.Add(new QShapeItem(0.0f, 50f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(0.0f, 17f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(15f, 17f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(15f, 12f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(5f, 12f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(18f, 5f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(31f, 12f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(21f, 12f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(21f, 17f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape23.Items.Add(new QShapeItem(100f, 17f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape23.Items.Add(new QShapeItem(100f, 50f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape23.ResetChanged();
      this.Add((QShape) shape23);
      QBaseShape shape24 = new QBaseShape(QBaseShapeType.RectangleShapedWindow.ToString(), QBaseShapeType.RectangleShapedWindow, new Size(100, 20), new Rectangle(2, 2, 96, 16));
      shape24.SetShapeType(QShapeType.ShapedWindow);
      shape24.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape24.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape24.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape24.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape24.ResetChanged();
      this.Add((QShape) shape24);
      QBaseShape shape25 = new QBaseShape(QBaseShapeType.RoundedRectangleShapedWindow.ToString(), QBaseShapeType.RoundedRectangleShapedWindow, new Size(100, 20), new Rectangle(3, 3, 94, 14));
      shape25.SetShapeType(QShapeType.ShapedWindow);
      shape25.Items.Add(new QShapeItem(5f, 19f, 3f, 19f, 1f, 17f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape25.Items.Add(new QShapeItem(1f, 15f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape25.Items.Add(new QShapeItem(1f, 5f, 1f, 3f, 3f, 1f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape25.Items.Add(new QShapeItem(5f, 1f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape25.Items.Add(new QShapeItem(95f, 1f, 97f, 1f, 99f, 3f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape25.Items.Add(new QShapeItem(99f, 5f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape25.Items.Add(new QShapeItem(99f, 15f, 99f, 17f, 97f, 19f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape25.Items.Add(new QShapeItem(95f, 19f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape25.ResetChanged();
      this.Add((QShape) shape25);
      QBaseShape shape26 = new QBaseShape(QBaseShapeType.RibbonForm.ToString(), QBaseShapeType.RibbonForm, new Size(100, 100), new Rectangle(3, 3, 94, 94));
      shape26.SetShapeType(QShapeType.ShapedWindow);
      shape26.Items.Add(new QShapeItem(0.0f, 7f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape26.Items.Add(new QShapeItem(7f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape26.Items.Add(new QShapeItem(93f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape26.Items.Add(new QShapeItem(100f, 7f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape26.Items.Add(new QShapeItem(100f, 93f, 100f, 98f, 98f, 100f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape26.Items.Add(new QShapeItem(93f, 100f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape26.Items.Add(new QShapeItem(7f, 100f, 2f, 100f, 0.0f, 98f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape26.Items.Add(new QShapeItem(0.0f, 93f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape26.ResetChanged();
      this.Add((QShape) shape26);
      QBaseShape shape27 = new QBaseShape(QBaseShapeType.SquareInputBox.ToString(), QBaseShapeType.SquareInputBox, new Size(100, 20), new Rectangle(1, 1, 98, 18));
      shape27.SetShapeType(QShapeType.InputBox);
      shape27.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape27.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape27.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape27.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape27.ResetChanged();
      this.Add((QShape) shape27);
      QBaseShape shape28 = new QBaseShape(QBaseShapeType.RoundedInputBox.ToString(), QBaseShapeType.RoundedInputBox, new Size(100, 20), new Rectangle(3, 1, 94, 18));
      shape28.SetShapeType(QShapeType.InputBox);
      shape28.Items.Add(new QShapeItem(0.0f, 5f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape28.Items.Add(new QShapeItem(5f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape28.Items.Add(new QShapeItem(95f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape28.Items.Add(new QShapeItem(100f, 5f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape28.Items.Add(new QShapeItem(100f, 15f, 100f, 18f, 98f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape28.Items.Add(new QShapeItem(95f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape28.Items.Add(new QShapeItem(5f, 20f, 2f, 20f, 0.0f, 18f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape28.Items.Add(new QShapeItem(0.0f, 15f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      this.Add((QShape) shape28);
      QBaseShape shape29 = new QBaseShape(QBaseShapeType.RoundedInputBox2.ToString(), QBaseShapeType.RoundedInputBox2, new Size(100, 20), new Rectangle(2, 1, 96, 18));
      shape29.SetShapeType(QShapeType.InputBox);
      shape29.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape29.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape29.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape29.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape29.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape29.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape29.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape29.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape29.ResetChanged();
      this.Add((QShape) shape29);
      QBaseShape shape30 = new QBaseShape(QBaseShapeType.SquareButton.ToString(), QBaseShapeType.SquareButton, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape30.SetShapeType(QShapeType.Button);
      shape30.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape30.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape30.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape30.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape30.ResetChanged();
      this.Add((QShape) shape30);
      QBaseShape shape31 = new QBaseShape(QBaseShapeType.RoundedButton.ToString(), QBaseShapeType.RoundedButton, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape31.SetShapeType(QShapeType.Button);
      shape31.Items.Add(new QShapeItem(4f, 20f, 2f, 20f, 0.0f, 18f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape31.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape31.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape31.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape31.Items.Add(new QShapeItem(96f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape31.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape31.Items.Add(new QShapeItem(100f, 16f, 100f, 18f, 98f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape31.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape31.ResetChanged();
      this.Add((QShape) shape31);
      QBaseShape shape32 = new QBaseShape(QBaseShapeType.RoundedButton2.ToString(), QBaseShapeType.RoundedButton2, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape32.SetShapeType(QShapeType.Button);
      shape32.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape32.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape32.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape32.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape32.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape32.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape32.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape32.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape32.ResetChanged();
      this.Add((QShape) shape32);
      QBaseShape shape33 = new QBaseShape(QBaseShapeType.InputBoxRoundedDropDownButton.ToString(), QBaseShapeType.InputBoxRoundedDropDownButton, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape33.SetShapeType(QShapeType.Button);
      shape33.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape33.Items.Add(new QShapeItem(95f, 0.0f, 98f, 0.0f, 100f, 2f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape33.Items.Add(new QShapeItem(100f, 5f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape33.Items.Add(new QShapeItem(100f, 15f, 100f, 18f, 98f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape33.Items.Add(new QShapeItem(95f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape33.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape33.ResetChanged();
      this.Add((QShape) shape33);
      QBaseShape shape34 = new QBaseShape(QBaseShapeType.InputBoxRoundedDropDownButtonLeft.ToString(), QBaseShapeType.InputBoxRoundedDropDownButtonLeft, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape34.SetShapeType(QShapeType.Button);
      shape34.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape34.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape34.Items.Add(new QShapeItem(5f, 20f, 2f, 20f, 0.0f, 18f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape34.Items.Add(new QShapeItem(0.0f, 15f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape34.Items.Add(new QShapeItem(0.0f, 5f, 0.0f, 2f, 2f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape34.Items.Add(new QShapeItem(5f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape34.ResetChanged();
      this.Add((QShape) shape34);
      QBaseShape shape35 = new QBaseShape(QBaseShapeType.InputBoxRoundedDropDownButton2.ToString(), QBaseShapeType.InputBoxRoundedDropDownButton2, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape35.SetShapeType(QShapeType.Button);
      shape35.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape35.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape35.Items.Add(new QShapeItem(96f, 0.0f, 100f, 0.0f, 100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape35.Items.Add(new QShapeItem(100f, 4f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape35.Items.Add(new QShapeItem(100f, 16f, 100f, 20f, 100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape35.Items.Add(new QShapeItem(96f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape35.ResetChanged();
      this.Add((QShape) shape35);
      QBaseShape shape36 = new QBaseShape(QBaseShapeType.InputBoxRoundedDropDownButtonLeft2.ToString(), QBaseShapeType.InputBoxRoundedDropDownButtonLeft2, new Size(100, 20), new Rectangle(0, 0, 100, 20));
      shape36.SetShapeType(QShapeType.Button);
      shape36.Items.Add(new QShapeItem(100f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape36.Items.Add(new QShapeItem(100f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape36.Items.Add(new QShapeItem(4f, 20f, 0.0f, 20f, 0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape36.Items.Add(new QShapeItem(0.0f, 16f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape36.Items.Add(new QShapeItem(0.0f, 4f, 0.0f, 0.0f, 0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape36.Items.Add(new QShapeItem(4f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape36.ResetChanged();
      this.Add((QShape) shape36);
      QBaseShape shape37 = new QBaseShape(QBaseShapeType.RibbonShowDialogButton.ToString(), QBaseShapeType.RibbonShowDialogButton, new Size(20, 20), new Rectangle(4, 3, 14, 15));
      shape37.SetShapeType(QShapeType.Button);
      shape37.Items.Add(new QShapeItem(0.0f, 20f, AnchorStyles.Bottom | AnchorStyles.Left, true));
      shape37.Items.Add(new QShapeItem(0.0f, 0.0f, AnchorStyles.Top | AnchorStyles.Left, true));
      shape37.Items.Add(new QShapeItem(20f, 0.0f, AnchorStyles.Top | AnchorStyles.Right, true));
      shape37.Items.Add(new QShapeItem(20f, 16f, 20f, 19f, 19f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape37.Items.Add(new QShapeItem(16f, 20f, AnchorStyles.Bottom | AnchorStyles.Right, true));
      shape37.ResetChanged();
      this.Add((QShape) shape37);
    }

    public int IndexOf(QBaseShapeType type)
    {
      for (int index = 0; index < this.Count; ++index)
      {
        if (this[index] is QBaseShape qbaseShape && qbaseShape.BaseShapeType == type)
          return index;
      }
      return -1;
    }

    public bool Contains(QBaseShapeType type) => this.IndexOf(type) >= 0;

    public QShape this[QBaseShapeType type]
    {
      get
      {
        int index = this.IndexOf(type);
        return index >= 0 ? this[index] : (QShape) null;
      }
    }
  }
}
